tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
cask "adoptopenjdk/openjdk/adoptopenjdk8"
brew "openssl@1.1"
brew "aria2"
brew "awscli"
brew "curl"
brew "emacs"
brew "ffmpeg"
brew "git"
brew "gradle"
brew "gradle-completion"
brew "kotlin"
brew "mas"
brew "node"
brew "pidcat"
brew "scrcpy"
brew "unrar"
brew "wget"
brew "youtube-dl"
brew "zsh"
mas "Magnet", id: 441258766
mas "Slack", id: 803453959
mas "Telegram", id: 747648890
mas "WhatsApp", id: 1147396723
